### ISSUE TITLE
Guidelines pp 2/3

### ISSUE THREAD

**Issue by plcrouse** [ChemEngUP/techreports#2]
Please move text at the bottom of p3 to b4 Table1, and correct line spacing.

**Comment by plcrouse** [comment]
Kom ons begin van voor af. Ek moet die titel v/d lot verander

**Comment by alchemyst** [comment]
The text at the bottom of page 3 is currently _part_ of Table 1. Would you prefer that I move it to the last part of section 2 (Format)?

**Comment by plcrouse** [comment]
Apologies, I didn't read it as a part of Table 1. It looked like a formatting error. I think it would be more appropriate as the last part of section 2, yes. Not imperative; your call.

**Comment by alchemyst** [comment]
Notice there is both a "Close and comment" and "Comment" button. Use the "Comment" button to make a comment and keep the issue open, so that I can close it when I resolve it.
