### ISSUE TITLE
Guidelines: change requests

### ISSUE THREAD

**Issue by plcrouse** [ChemEngUP/techreports#3]
- [x] Last bullet p4: 'mathematical functions and operators'. This will inlcude d, +, -, etc.
- [x] p5, 5th bullet: 'different brackets' -> 'braces, brackets, and parentheses'.
- [ ] p5, bottom: perhaps include 'Note the right-harpoon-over-left-harpoon symbol is unicode character 21cc'. Most students/people search & can't find it.
- [ ] Simlarly, after the first sentence p6, add: 'The multiplcation sign can be accessed as unicode character 00D7. (Lower case or upper case D, and CC above?)
- [ ] Figure 2: It will make my life easier if the nomenclature list is written as 'b Constant (s)' etc, ie with the units in parenteses immediately after the text exaplaining the symbol.
- [ ] Please can we make the heading for p9 Appendix A, and its page number A1.
- [x] p17: Please add a paragraph to Section 4.6.1, before Apparatus. "Materials List the materials and chemicals used, their purities, and suppliers".
- [x] p23: Change the Buys reference to leading capitals in the title for consistency. Ie, 'Research Guide for Postgraduate Students'.
- [x] p27: In the book ref examples, for one at least add an edition. Students keep asking. Eg, " ... Membranes, 2nd edition, McGraw-Hill, NY'.
- [x] p27: Strathmann paper example: close space between the volume and edition numbers, ie, should be 9(2).
- [x] p28: Report, thesis or similar: space the examples out as for the other example entries.
- [x] p28: Bottom of page, the Mazur title to be with lower case letters, ie, 'Gas separation membranes - now and tomorrow'.

**Comment by plcrouse** [comment]
p5, 5th bullet: 'different brackets' -> 'braces, brackets, and parentheses'.

**Comment by plcrouse** [comment]
p5, bottom: perhaps include 'Note the right-harpoon-over-left-harpoon symbol is unicode character 21cc'.
Most students/people search & can't find it.

**Comment by plcrouse** [comment]
Simlarly, after the first sentence p6, add: 'The multiplcation sign can be accessed as unicode character 00D7. (Lower case or upper case D, and CC above?)

**Comment by plcrouse** [comment]
Figure 2: 
1) It will make my life easier if the nomenclature list is written as 'b Constant (s)' etc, ie with the units in parenteses immediately after the text exaplaining the symbol.
2) Please can we make the heading for p9 Appendix A, and its page number A1.

**Comment by plcrouse** [comment]
p17: Please add a paragraph to Section 4.6.1, before Apparatus. "Materials  List the materials and chemicals used, their purities, and suppliers".

**Comment by plcrouse** [comment]
p23: Change the Buys reference to leading capitals in the title for consistency. Ie, 'Research Guide for Postgraduate Students'.

**Comment by plcrouse** [comment]
p27: 
1) In the book ref examples, for one at least add an edition. Students keep asking. Eg, " ... Membranes, 2nd edition, McGraw-Hill, NY'.
2) Strathmann paper example: close space between the volume and edition numbers, ie, should be 9(2).

**Comment by plcrouse** [comment]
p28: 

1. Report, thesis or similar: space the examples out as for the other example entries.
2. Bottom of page, the Mazur title to be with lower case letters, ie, 'Gas separation membranes - now and tomorrow'.

**Comment by plcrouse** [comment]
Dankie!

**Comment by alchemyst** [comment]
You would have made my life a lot easier by loading each of these as a separate issue.

**Comment by alchemyst** [comment]
1. Computer-related stuff as sent by e-mail
1. The nomenclature list having right aligned units is just as easy as having the units in parenthese
1. I dislike restarting the numbering for the appendix as it makes it harder to find that page using the table of contents.

**Comment by plcrouse** [comment]
Thanks & noted, noted, noted.
